# Site settings
title: Leslie Dickinson | Portfolio and Blog
description: Leslie Dickinson is a software quality engineer sharing selected projects, career experience, and writing about quality, technology, and people.
baseurl: "" # the subpath of your site, e.g. /blog
#baseurl: "" # the subpath of your site, e.g. /blog
domain: "lesliedickinson.dev"
#domain: "lespam.fun"
url: "https://lesliedickinson.dev" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# url: "https://lespam.fun"
# User settings
username: Leslie Dickinson
user_title: SDET and Quality Engineer | Test Automation | Enterprise Systems
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--more-->
email: lesliepbv@gmail.com
#blog_url: /blog
# twitter_username: lorem_ipsum
instagram_username: artechnolution
#instagram_username: lespam._
#instagram_username: autistita
#facebook_username: LesPamB
linkedin_username: lespam
github_username:  lespam
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['src' , 'node_modules']
