# Site settings
title: Les
description: Sitio web de Leslie Brenes.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Leslie Brenes
user_description: <div class="section">Soy Leslie Pamela. Algunos me llaman lespam for mi facebook. Tengo una visión holística del mundo.  
    Estudié Ingeniería en Computación en el ITAM.  
    Actualmente trabajo como QA Engineer para Sonatafy Technology.  
    Soy una persona neurodivergente.  
    Me gusta la tecnología.
user_title: QA Engineer
#email: lesliepbv@gmail.com
email: leslie.brenes@sonatafy.com
# twitter_username: lorem_ipsum
instagram_username: artechnolution
#instagram_username: lespam._
#instagram_username: autistita
#facebook_username: LesPamB
linkedin_username: lespam
github_username:  lespam
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
