# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: lespam\\ #abajo
#logo: /assets/img/repository-logo.png
#logo: https://avatars.githubusercontent.com/u/23329703?v=4

is_user_page: true
owner_gravatar_url: "https://github.com/github.png"
owner_name: "lespam"

email: lesliepbv@gmail.com
description: "I'm passionate about all things tech! Ever since I was a kid, I was always the one helping other people out with difficulties with the computer and reading the documentation.
I've worked on Software Development for over 5 years.

When I'm using an app, I'm always taking note on  the user flow design and the issues I find. I love to do User Research, and being a visionary of the potential tech innovations of tomorrow. I'm also a hard worker, in my time as a Software Quality Assurance Engineer, I work daily on things that involve software design, writing source code, reviewing code, testing, documenting, debugging and ensuring compliance. I have a "focus and flow!" mentality when I'm stimulated, and constantly push myself to go beyond expectations. Above all -- I just love doing what I do, testing, coding, making content related to technology, and helping people with what I create.

I would love to contribute my talents to your brand and show how much of an asset I can be to your team.

Contact me, if you'd like to work with me, feel free to reach out!"
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
domain: "lespam.fun"
url: "https://lespam.fun" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lespam._
github_username:  lespam

# Build settings
#remote_theme: b2a3e8/jekyll-theme-console
#theme: jekyll-theme-console
theme: jekyll-theme-hacker

#show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
header_pages: 
  - index.markdown
  - about.markdown
footer: 'Let the revolution begin. Estoy a un tap de distancia :)'
#google_analytics: 'G-Z1FXPBGQSR'
#google_analytics: G-Z1FXPBGQSR
listen_for_clients_preferred_style: true
style: hacker # dark (default), light or hacker
#lang: es

plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
